### ISSUE TITLE
Add Splash Screen

### ISSUE THREAD

**Issue by yashpaneliya** [clubgamma/Spotify-UI-Clone-Flutter#1]
As we all know that splash screen of any app sets the first impression of app, so why don't we start with it.

There are two ways to add splash screen in flutter.

1. Go with Native
2. Go with Flutter

You can go with any of this but make sure you add in description that which path you have chosen so that other won't get confused. 

And you might have seen the splash screen of original Spotify app, so take it as an example.

You can find all the assets over [here](https://newsroom.spotify.com/media-kit/logo-and-brand-assets/).

**Comment by Dabjazz** [comment]
Sir, I would like to contribute to this project.

**Comment by jayskhatri** [comment]
> Sir, I would like to contribute to this project.
Go ahead 👍

**Comment by jayskhatri** [comment]
If you are not working on this issue then please remove yourself from the assignee 😀

**Comment by BRO3886** [comment]
can I work on it as well?

**Comment by Dabjazz** [comment]
@jayskhatri  Sir, Kindly review my pull request. I have added the Splash Screen.
