### ISSUE TITLE
NavigationBar in homepage

### ISSUE THREAD

**Issue by yashpaneliya** [clubgamma/Spotify-UI-Clone-Flutter#2]
Add a **NavigationBar** in the homepage of the application.

Items in the NavigationBar are as follows:

1. Home
2. Search
3. Your Library

Ex.
![Screenshot_20200929-223642](https://user-images.githubusercontent.com/58077762/94590728-c9e43380-02a4-11eb-8388-d57f01166fe7.png)

**Comment by brainless-coder** [comment]
I would like to work on this issue

**Comment by jayskhatri** [comment]
> I would like to work on this issue

Go ahead 👍

**Comment by jayskhatri** [comment]
If you are not working on this issue then please remove yourself from the assignee 😀

**Comment by BRO3886** [comment]
Can I work on this if @brainless-coder has not responded?

**Comment by brainless-coder** [comment]
> If you are not working on this issue then please remove yourself from the assignee 😀

I am working on this issue, will create a PR soon

**Comment by BRO3886** [comment]
oh sorry, I didn't see, have pushed a small commit for this and defined a project structure

**Comment by brainless-coder** [comment]
@BRO3886 great job, as you made a PR for this issue, so i unassigned myself from this issue
