### ISSUE TITLE
Add Recently Played View

### ISSUE THREAD

**Issue by yashpaneliya** [clubgamma/Spotify-UI-Clone-Flutter#3]
Add a **horizontal scrolling cards** view for the recently played songs or playlists.

> You can use dummy data for cards.

Also link each card with respective screens. If that screen is not created the you can create that also. For that refer this issue.

Ex.

![Recently played](https://user-images.githubusercontent.com/58077762/94594500-2a747000-02a7-11eb-9553-0fd24f4fc307.png)

**Comment by rish07** [comment]
Hey @yashpaneliya  I would like to work on this issue for hacktoberfest

**Comment by jayskhatri** [comment]
> Hey @yashpaneliya I would like to work on this issue for hacktoberfest. Let me know when I can start

Hey @rish07 👋

You can start working on it 👍, make sure you make a pull request in 1-31 October.
For more details, https://clubgamma.github.io/hacktoberfest

**Comment by rish07** [comment]
Hey @jayskhatri, it would be great if you could merge the existing PRs so I can start working on this issue, cause working on the same file would create merge conflicts because as of now, there is no code in the repo

**Comment by harshptl14** [comment]
Hey @rish07, sorry for the inconvenience😓 I have merged those basic screen layout PRs. 
#### **You can start working on these Issues🚀**
