### ISSUE TITLE
Add Settings Page

### ISSUE THREAD

**Issue by yashpaneliya** [clubgamma/Spotify-UI-Clone-Flutter#6]
1. Add settings Icon Button in AppBar on homepage

2. Link the settings page with this button.
    
    Features:
    - Profile info
    - It's a long list so you can refer to the original app 😉

**Comment by michaeldadzie** [comment]
@yashpaneliya can i work on this issue?

**Comment by michaeldadzie** [comment]
<b>added settings page #16 </b>

**Comment by yash2189** [comment]
Hi @yashpaneliya Some of the features are normalizing volume , broadcast status ,etc do we need to implement them as well?

**Comment by yashpaneliya** [comment]
> Hi @yashpaneliya do we just need to add the features or should they be made working like some of the features are related to broadcasting,etc in the original app
> 

Hey @yash2189 , as this is just a UI Clone of Spotify, so our main focus is creating UI, but if you are able to add working feature then it'll be a cherry on top.

Happy Hacking!!!
