### ISSUE TITLE
Add search page

### ISSUE THREAD

**Issue by yashpaneliya** [clubgamma/Spotify-UI-Clone-Flutter#7]
Create a search page and link with the NavigationBar on homepage

Features :
1. Search Bar (In working condition)
2. Cards for category
3. Links the cards with respective pages

Ex.

![Screenshot_20200929-223736](https://user-images.githubusercontent.com/58077762/94602172-2568ee00-02b2-11eb-9e06-2c6fb07fcf63.png)

**Comment by woinbo** [comment]
Is this issue, still available for the #hacktoberfest 2021 or not? @yashpaneliya
